#############################################################################
# Makefile for building: RNote
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  RNote.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile RNote.pro -config release/
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RNote1.0.0
DISTDIR = /media/rushikesh/MacOS/MTXOS/VisualStudioProjects/RNote/RNote/.tmp/RNote1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		rwindow.cpp \
		tab.cpp qrc_Imagicon.cpp \
		moc_rwindow.cpp \
		moc_tab.cpp
OBJECTS       = main.o \
		rwindow.o \
		tab.o \
		qrc_Imagicon.o \
		moc_rwindow.o \
		moc_tab.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RNote.pro rwindow.h \
		tab.h \
		tabData.h main.cpp \
		rwindow.cpp \
		tab.cpp
QMAKE_TARGET  = RNote
DESTDIR       = 
TARGET        = RNote


first: all
####### Build rules

RNote: ui_rwindow.h ui_tab.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RNote.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RNote.pro \
		Imagicon.qrc
	$(QMAKE) -o Makefile RNote.pro -config release/
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
RNote.pro:
Imagicon.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile RNote.pro -config release/

qmake_all: FORCE


all: Makefile RNote

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Imagicon.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents rwindow.h tab.h tabData.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp rwindow.cpp tab.cpp $(DISTDIR)/
	$(COPY_FILE) --parents rwindow.ui tab.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Imagicon.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Imagicon.cpp
qrc_Imagicon.cpp: Imagicon.qrc \
		/usr/lib/qt5/bin/rcc \
		Images/GNU.ico \
		Images/RNote.ico
	/usr/lib/qt5/bin/rcc -name Imagicon Imagicon.qrc -o qrc_Imagicon.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_rwindow.cpp moc_tab.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_rwindow.cpp moc_tab.cpp
moc_rwindow.cpp: rwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /media/rushikesh/MacOS/MTXOS/VisualStudioProjects/RNote/RNote/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/rushikesh/MacOS/MTXOS/VisualStudioProjects/RNote/RNote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -IE:/Qt/Qt5.9.9/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IE:/Qt/Qt5.9.9/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IE:/Qt/Qt5.9.9/Tools/mingw530_32/i686-w64-mingw32/include -IE:/Qt/Qt5.9.9/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IE:/Qt/Qt5.9.9/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IE:/Qt/Qt5.9.9/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward rwindow.h -o moc_rwindow.cpp

moc_tab.cpp: tab.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /media/rushikesh/MacOS/MTXOS/VisualStudioProjects/RNote/RNote/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/rushikesh/MacOS/MTXOS/VisualStudioProjects/RNote/RNote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -IE:/Qt/Qt5.9.9/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IE:/Qt/Qt5.9.9/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IE:/Qt/Qt5.9.9/Tools/mingw530_32/i686-w64-mingw32/include -IE:/Qt/Qt5.9.9/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IE:/Qt/Qt5.9.9/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IE:/Qt/Qt5.9.9/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward tab.h -o moc_tab.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_rwindow.h ui_tab.h
compiler_uic_clean:
	-$(DEL_FILE) ui_rwindow.h ui_tab.h
ui_rwindow.h: rwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic rwindow.ui -o ui_rwindow.h

ui_tab.h: tab.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic tab.ui -o ui_tab.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp rwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

rwindow.o: rwindow.cpp rwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		ui_rwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QDebug \
		tab.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMessageBox \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmessagebox.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QString \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QFileDialog \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qfiledialog.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdir.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfileinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QPlainTextEdit \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qplaintextedit.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtextedit.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextdocument.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpen.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qabstracttextdocumentlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qglyphrun.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrawfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontdatabase.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QUrl \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/QDesktopServices \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qdesktopservices.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstandardpaths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rwindow.o rwindow.cpp

tab.o: tab.cpp tab.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		ui_tab.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QColorDialog \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qcolordialog.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tab.o tab.cpp

qrc_Imagicon.o: qrc_Imagicon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Imagicon.o qrc_Imagicon.cpp

moc_rwindow.o: moc_rwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rwindow.o moc_rwindow.cpp

moc_tab.o: moc_tab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tab.o moc_tab.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/RNote/bin || mkdir -p $(INSTALL_ROOT)/opt/RNote/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/RNote/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/RNote/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/RNote/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/RNote/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

